version: '3.8'

services:
  app:
    build:
      context: .
    env_file: .env
    environment:
      - LEIN_REPL_HOST=0.0.0.0
      - LEIN_REPL_PORT=40263
    ports:
      - 40263:40263
    volumes:
      - .:/workspace
      - ~/.lein:/root/.lein
      - ~/.m2:/root/.m2
      - ~/.staxchg.conf:/root/.staxchg.conf 
