#!/bin/sh
':' //; exec `command -v nodejs || command -v node` "$0" "$@"


var child_process = require('child_process');
var path = require('path');

function requireHljs(modulesDir) {
	try {
		return require(modulesDir + path.sep + 'highlight.js');
	} catch (err) {
		return null;
	}
}

function npmModulesDir() {
	try {
		return child_process
			.execSync('npm root -g')
			.toString()
			.trim();
	} catch (err) {
		return null;
	}
}

function yarnModulesDir() {
	try {
		var root = child_process
			.execSync('yarn global dir')
			.toString()
			.trim();

		return root + path.sep + 'node_modules';
	} catch (err) {
		return null;
	}
}

var hljs = requireHljs(npmModulesDir())
	|| requireHljs(yarnModulesDir())
	|| process.exit(1);
var fs = require('fs');

var code = fs.readFileSync(0).toString(); // STDIN_FILENO = 0
var result = (process.argv.length > 2)
	? hljs.highlightAuto(code, process.argv.slice(2))
	: hljs.highlightAuto(code);

console.log(result.value);

