#!/bin/sh
':' //; exec `command -v nodejs || command -v node` "$0" "$@"


var child_process = require('child_process');
var path = require('path');

function requireHljs(modulesDir, languages) {
	try {
		var libDir = modulesDir + path.sep + 'highlight.js' + path.sep + 'lib';
		var hljs = require(libDir + path.sep + 'core');
		var langDir = libDir + path.sep + 'languages';

		for (l of languages) {
			hljs.registerLanguage(l, require(langDir + path.sep + l));
		}

		return hljs;
	} catch (err) {
		return null;
	}
}

function npmModulesDir() {
	try {
		return child_process
			.execSync('npm root -g')
			.toString()
			.trim();
	} catch (err) {
		return null;
	}
}

function yarnModulesDir() {
	try {
		var root = child_process
			.execSync('yarn global dir')
			.toString()
			.trim();

		return root + path.sep + 'node_modules';
	} catch (err) {
		return null;
	}
}

var languages = process.argv.slice(2);
var hljs = requireHljs(npmModulesDir(), languages)
	|| requireHljs(yarnModulesDir(), languages)
	|| process.exit(1);

var fs = require('fs');

var code = fs.readFileSync(0).toString(); // STDIN_FILENO = 0
var result = (process.argv.length > 2)
	? hljs.highlightAuto(code, process.argv.slice(2))
	: hljs.highlightAuto(code);

console.log(result.value);

